### PR TITLE
Added custom event to fix email confirmation system

### LINKED ISSUE #153: Email registration check is not working
## Steps to reproduce

- Enable email registration confirmation
- Try to use the signup endpoint

## Expected results

- The user is set to disabled
- An email gets send to the user with an activation link

## Actual results

- The user is active
- No email is send

## The cause

The problem is that `EmailConfirmationListener` is doing a `if (!$user instanceof UserInterface)` check. But the `FormEvent` and the form data are not of type `UserInterface` but of type `Registration`.

### PR DESCRIPTION
**Pull request by fkrauthan**
Closes #153

## Subject

- Added new event class `UserFormEvent`
- Switched the `REGISTRATION_SUCCESS` event to `UserFormEvent`
- Updated `EmailConfirmationListener` to use new event type to make it work

### CODE REVIEW

File: src/Event/UserFormEvent.php [hunk 1]
```diff
@@ -0,0 +1,73 @@
...
+
+namespace Nucleos\ProfileBundle\Event;
+
+use Nucleos\UserBundle\Model\UserInterface;
+use Symfony\Component\Form\FormInterface;
+use Symfony\Component\HttpFoundation\Request;
+use Symfony\Component\HttpFoundation\Response;
+use Symfony\Contracts\EventDispatcher\Event;
+
+class UserFormEvent extends Event
```
Comment (core23) [inline src/Event/UserFormEvent.php:20]: Can you please extend the `Nucleos\UserBundle\Event\FormEvent` otherwise this is a BC break for someone that listens on the `REGISTRATION_SUCCESS` event.

**Review by core23 — CHANGES_REQUESTED** [review]

File: src/Event/UserFormEvent.php (hunk 1 above)
Comment (fkrauthan) [reply src/Event/UserFormEvent.php:20]: Unfortunately you can't as `FormEvent` is a final class in the UserBundle (it was my initial thought to begin with). If you remove that I am happy to update this PR.

Btw this event in general is not compatible with the relevant FOSUserBundle event (might be worth pointing out). As the FOSUserBundle has as FormData the `UserInterface` instance and not a separate registration form entity.

Comment (core23) [reply src/Event/UserFormEvent.php:20]: > Unfortunately you can't as `FormEvent` is a final class in the UserBundle (it was my initial thought to begin with). If you remove that I am happy to update this PR.

This is the only way to stay BC. Feel free to open a PR in the `UserBundle`.

> Btw this event in general is not compatible with the relevant FOSUserBundle event (might be worth pointing out).

This might be right. My initial idea was to alias all FOS classes. There was a [POC](https://github.com/nucleos/FOSUserBundlePolyfill), but I'm not sure if this ever worked. The time consumption for this project was too much for me so I archived this.

The current project has some 100% copy & paste parts from the FOS community but there are also some major changes, e.g. splitting the project in the user and profile bundle. This is intended, because the active development stopped a long time ago.

**Comment by fkrauthan** [comment]
Created merge request in nucleos/NucleosUserBundle#200 to make `UserFormEvent` extend `FormEvent`. This will require a new release of the user bundle to be compatible.

**Comment by core23** [comment]
There is a new 1.7.0 release of the user bundle. Please bump the user-bundle version inside the `composer.json` file.

**Comment by fkrauthan** [comment]
> There is a new 1.7.0 release of the user bundle. Please bump the user-bundle version inside the `composer.json` file.

Done

File: src/Event/UserFormEvent.php [hunk 2]
```diff
@@ -0,0 +1,38 @@
...
+{
+    /**
+     * @var UserInterface
+     */
+    private $user;
+
+    public function __construct(UserInterface $user, FormInterface $form, Request $request)
+    {
+        parent::__construct($form, $request);
+
```
Comment (core23) [inline src/Event/UserFormEvent.php:30]:
```suggestion

```

File: src/Event/UserFormEvent.php [hunk 3]
```diff
@@ -0,0 +1,37 @@
...
+namespace Nucleos\ProfileBundle\Event;
+
+use Nucleos\UserBundle\Event\FormEvent ;
+use Nucleos\UserBundle\Model\UserInterface;
+use Symfony\Component\Form\FormInterface;
+use Symfony\Component\HttpFoundation\Request;
+use Symfony\Component\HttpFoundation\Response;
+
+class UserFormEvent extends FormEvent
```
Comment (core23) [inline src/Event/UserFormEvent.php:20]:
```suggestion
final class UserFormEvent extends FormEvent
```

**Comment by core23** [comment]
Thanks @fkrauthan
